POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
  "title": "NewBlog",
  "author": "Max Verstappen",
  "url": "https://google.com",
  "likes": "10",
}

####
GET http://localhost:3003/api/blogs
Content-Type: application/json